"""Deploy artifact generation for `rya deploy`.

Turns an agent project into a self-contained, deployable container: the agent
code is baked into the image (not mounted), so the same artifact runs on Fly,
Render, ECS, or any Docker host. State stays external (Postgres via
RYA_DATABASE_URL), per the substrate-agnostic design.

If a local ``rya-*.whl`` is present in the project (a pre-publish build), the
Dockerfile installs that; otherwise it installs ``rya`` from PyPI.
"""

from __future__ import annotations

import glob
import re
from pathlib import Path
from typing import List, Optional


def _find_wheel(root: Path) -> Optional[str]:
    hits = sorted(glob.glob(str(root / "rya-*.whl"))) or sorted(glob.glob(str(root / "*.whl")))
    return Path(hits[0]).name if hits else None


def _app_name(name: str) -> str:
    slug = re.sub(r"[^a-z0-9-]", "-", name.lower()).strip("-")
    return slug or "rya-agent"


def dockerfile(root: Path) -> str:
    wheel = _find_wheel(root)
    if wheel:
        install = f'COPY {wheel} /tmp/{wheel}\nRUN pip install --no-cache-dir "/tmp/{wheel}[api,postgres,llm,mcp]"'
    else:
        install = 'RUN pip install --no-cache-dir "rya[api,postgres,llm,mcp]"'
    return f"""# Generated by `rya deploy` — a self-contained agent runtime image.
FROM python:3.12-slim
WORKDIR /app
{install}
COPY . /app/project
WORKDIR /app/project
EXPOSE 8787
CMD ["rya", "serve", "--host", "0.0.0.0", "--port", "8787"]
"""


DOCKERIGNORE = """.rya/
.venv/
venv/
__pycache__/
*.pyc
.git/
.env
"""


def fly_toml(name: str) -> str:
    app = _app_name(name)
    return f"""# Generated by `rya deploy`. Deploy: fly launch --copy-config --no-deploy && fly deploy
app = "{app}"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8787
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  size = "shared-cpu-1x"
  memory = "512mb"
"""


def render_yaml(name: str) -> str:
    app = _app_name(name)
    return f"""# Generated by `rya deploy`. Connect this repo in Render; it provisions a web service.
services:
  - type: web
    name: {app}
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: RYA_DATABASE_URL
        sync: false
      - key: RYA_TOKEN
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
"""


def write_artifacts(root: Path) -> List[str]:
    from ..manifest import load_manifest

    name = load_manifest(root / "rya.agent.yaml").name
    files = {
        "Dockerfile": dockerfile(root),
        ".dockerignore": DOCKERIGNORE,
        "fly.toml": fly_toml(name),
        "render.yaml": render_yaml(name),
    }
    written = []
    for rel, content in files.items():
        (root / rel).write_text(content)
        written.append(rel)
    return written


def deploy_plan(target: str, manifest, root: Path) -> dict:
    name = _app_name(manifest.name)
    required = ["RYA_DATABASE_URL  # managed Postgres (durable runs)",
                "RYA_TOKEN         # operator API token"]
    if manifest.model.provider in ("auto", "anthropic"):
        required.append("ANTHROPIC_API_KEY # if using real Claude")
    required.append("RYA_WEBHOOK_SECRET (optional) # sign inbound webhooks")

    commands = {
        "fly": f"fly launch --copy-config --no-deploy && fly secrets set RYA_DATABASE_URL=… RYA_TOKEN=… && fly deploy",
        "render": "git push to a Render-connected repo (render.yaml provisions the service)",
        "docker": f"docker build -t {name} . && docker run -p 8787:8787 "
                  f"-e RYA_DATABASE_URL=… -e RYA_TOKEN=… {name}",
        "check": "(validation only — pass --target fly|render|docker for a deploy command)",
    }
    return {
        "appName": name,
        "requiredEnv": required,
        "command": commands.get(target, commands["check"]),
        "webhook": "POST /inbound on the deployed URL triggers a run",
    }
